Readio/src/main/java/ninegle/Readio/admin/api/UserController.java, Readio/src/main/java/ninegle/Readio/admin/app/JwtTokenProvider.java, Readio/src/main/java/ninegle/Readio/admin/app/UserService.java, Readio/src/main/java/ninegle/Readio/admin/comfig/JwtAuthFilter.java, Readio/src/main/java/ninegle/Readio/admin/comfig/SecurityConfig.java, Readio/src/main/java/ninegle/Readio/admin/dto/TokenBody.java, Readio/src/main/java/ninegle/Readio/admin/dto/UserDetail.java
=> fix: security 로그아웃 수정

.github/ISSUE_TEMPLATE/fix-template.md, README.md, Readio/src/main/java/ninegle/Readio/admin/api/UserController.java, Readio/src/main/java/ninegle/Readio/admin/app/JwtTokenProvider.java, Readio/src/main/java/ninegle/Readio/admin/app/UserService.java, Readio/src/main/java/ninegle/Readio/admin/comfig/JwtAuthFilter.java, Readio/src/main/java/ninegle/Readio/admin/comfig/SecurityConfig.java, Readio/src/main/java/ninegle/Readio/admin/dto/TokenBody.java, Readio/src/main/java/ninegle/Readio/admin/dto/UserDetail.java
=> fix: security 로그아웃 버그 수정

Readio/build.gradle, Readio/docker-compose.elasticsearch.yml, Readio/elasticsearch/Dockerfile, Readio/src/main/java/ninegle/Readio/admin/app/JwtTokenProvider.java, Readio/src/main/java/ninegle/Readio/admin/config/JwtAuthFilter.java, Readio/src/main/java/ninegle/Readio/admin/config/JwtConfiguration.java, Readio/src/main/java/ninegle/Readio/admin/config/SecurityConfig.java, Readio/src/main/java/ninegle/Readio/book/controller/BookController.java, Readio/src/main/java/ninegle/Readio/book/domain/Author.java, Readio/src/main/java/ninegle/Readio/book/domain/Book.java, Readio/src/main/java/ninegle/Readio/book/domain/Category.java, Readio/src/main/java/ninegle/Readio/book/domain/Publisher.java, Readio/src/main/java/ninegle/Readio/book/dto/BookEsDto.java, Readio/src/main/java/ninegle/Readio/book/repository/AuthorRepository.java, Readio/src/main/java/ninegle/Readio/book/repository/BookRepository.java, Readio/src/main/java/ninegle/Readio/book/repository/BookSearchRepository.java, Readio/src/main/java/ninegle/Readio/book/repository/PublisherRepository.java, Readio/src/main/java/ninegle/Readio/book/service/BookService.java, Readio/src/main/java/ninegle/Readio/global/config/ElasticsearchIndexInitializer.java
Elastic Search 적용 완료
Dockerfile,docker-compose
book Entity 적용
=> Feat/entity add/1

Readio/src/main/java/ninegle/Readio/admin/config/SecurityConfig.java, Readio/src/main/java/ninegle/Readio/book/controller/BookController.java, frontend/package-lock.json, frontend/package.json, frontend/src/components/review/ReviewFilters.tsx, frontend/src/components/review/ReviewForm.tsx, frontend/src/components/review/ReviewList.tsx, frontend/src/pages/book/BookDetailPage.tsx, frontend/src/pages/book/BookReviewsPage.tsx, frontend/src/pages/member/MyPage.tsx, frontend/src/utils/api/reviewService.ts
- 리뷰 조회 연동
- 리뷰 등록 연동
Closes #32
=> feat: 리뷰 조회, 등록 API 연동

Readio/src/main/java/ninegle/Readio/book/controller/PreferenceController.java, Readio/src/main/java/ninegle/Readio/book/domain/Preference.java, Readio/src/main/java/ninegle/Readio/book/dto/BookIdRequestDto.java, Readio/src/main/java/ninegle/Readio/book/dto/BookPreferenceDto.java, Readio/src/main/java/ninegle/Readio/book/dto/BookPreferenceListDto.java, Readio/src/main/java/ninegle/Readio/book/mapper/PreferenceMapper.java, Readio/src/main/java/ninegle/Readio/book/repository/PreferencesRepository.java, Readio/src/main/java/ninegle/Readio/book/service/PreferenceService.java, frontend/src/components/review/ReviewFilters.tsx, frontend/src/components/review/ReviewForm.tsx, frontend/src/components/review/ReviewList.tsx, frontend/src/utils/api/reviewService.ts
=> feat: 도서 CRU 구현

frontend/src/App.tsx, frontend/src/components/book/CategoryRedirect.tsx, frontend/src/components/layout/NavBar.tsx, frontend/src/components/review/ReviewCard.tsx, frontend/src/components/review/ReviewList.tsx, frontend/src/components/ui/skeleton.tsx, frontend/src/contexts/AuthContext.tsx, frontend/src/interface/AuthContextType.tsx, frontend/src/interface/SignupForm.tsx, frontend/src/pages/book/BookDetailPage.tsx, frontend/src/pages/book/BookReviewsPage.tsx, frontend/src/pages/book/BooksPage.tsx, frontend/src/pages/library/LibraryDetailPage.tsx, frontend/src/pages/library/LibraryPage.tsx, frontend/src/pages/member/LoginPage.tsx, frontend/src/pages/member/SignupPage.tsx, frontend/src/pages/member/WishlistPage.tsx, frontend/src/types/book.ts, frontend/src/utils/api/authService.ts, frontend/src/utils/api/bookService.ts, frontend/src/utils/api/reviewService.ts, frontend/src/utils/validation/CheckoutValidation.tsx
- 리뷰 수정 API 연동
- 리뷰 삭제 API 연동
- toast 를 sonner 로 변경
Closes #45
=> feat: 리뷰 수정, 삭제 API 연동 및 toast를 sonner로 변경

frontend/src/pages/member/MyPage.tsx, frontend/src/types/user.ts, frontend/src/utils/api/userService.ts
- 포인트 조회 API 연동
- 회원정보 조회 API 연동
- 회원정보 수정 API 연동
- 구독 조회 API 연동
- 구독권 결제 API 연동
- 구독 취소 API 연동
Closes #47
=> feat: 마이페이지 API 연동

Readio/src/main/java/ninegle/Readio/library/domain/Library.java, frontend/package-lock.json, frontend/package.json, frontend/src/components/ui/radio-group.tsx, frontend/src/pages/book/BookDetailPage.tsx, frontend/src/pages/library/LibraryDetailPage.tsx, frontend/src/pages/library/LibraryPage.tsx, frontend/src/utils/api/bookService.ts, frontend/src/utils/api/libraryService.ts
- 라이브러리 목록 조회 API 연동
- 특정 라이브러리 책 목록 조회
- 새 라이브러리 생성
- 특정 라이브러리에 책 추가
- 특정 라이브러리 이름 수정
- 라이브러리 삭제
- 특정 라이브러리 책 삭제
Closes #49
=> feat: 라이브러리 api 연동

Readio/src/main/java/ninegle/Readio/library/domain/Library.java
=> fix: Library 테이블 명 수정

frontend/src/interface/FormErrors.tsx, frontend/src/interface/SignupForm.tsx, frontend/src/pages/member/SignupPage.tsx
=> fix: 핸드폰 번호 데이터 전송 수정

frontend/src/pages/MainPage.tsx, frontend/src/pages/book/BooksPage.tsx, frontend/src/pages/member/LoginPage.tsx, frontend/src/pages/member/SignupPage.tsx
- 신간 도서 제거
- 책 목록 조회 페이지 margin padding 축소
- 책 목록 조회 페이지 필터 제거
- 회원가입 페이지 비밀번호 입력 위치 변경
Closes #62
=> design: 불필요한 ui 제거 및 변경

.idea/libraries/Gradle__org_eclipse_angus_jakarta_mail_2_0_3.xml, .idea/libraries/Gradle__org_springframework_boot_spring_boot_starter_mail_3_4_4.xml, .idea/libraries/Gradle__org_springframework_spring_context_support_6_2_5.xml, .idea/modules/Readio.main.iml, .idea/modules/Readio.test.iml, Readio/build.gradle, Readio/src/main/java/ninegle/Readio/global/config/ApplicationConfig.java, Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailSender.java, Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java, Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailSender.java, Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailTemplateProvider.java, Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionManager.java, Readio/src/main/java/ninegle/Readio/user/service/UserService.java
=> [Feat] 메일서비스구현(구독결제, 취소, 회원가입)

frontend/src/components/layout/NavBar.tsx, frontend/src/pages/MainPage.tsx, frontend/src/pages/book/BooksPage.tsx, frontend/src/pages/book/EpubReaderPage.tsx, frontend/src/utils/api/bookService.ts, frontend/src/utils/api/categoryService.ts
책 카테고리별 조회
책 검색
카테고리 조회
Closes #72
=> feat: 책 관련 API 연동

Readio/src/main/java/ninegle/Readio/user/config/SecurityConfig.java
=> feat : 카테고리 목록 조회 권한 부여

frontend/src/pages/MainPage.tsx
=> [fix]메인페이지 히어로섹션 회원가입 버튼 삭제

frontend/src/components/layout/NavBar.tsx, frontend/src/pages/admin/AdminDashboard.tsx, frontend/src/types/publisher.ts, frontend/src/utils/api/publisherService.ts
- 관리자 책 추가
- 책 수정
- 책 삭제
- 출판사 추가
- 출판사 조회
=> feat: 관리자 API 연동

frontend/src/components/ui/PointChargeModal.tsx, frontend/src/pages/admin/AdminDashboard.tsx, frontend/src/pages/member/MyPage.tsx, frontend/src/pages/payment/CheckoutPage.tsx, frontend/src/pages/payment/SuccessPage.tsx
=> design: 토스페이 ui 개선

Readio/src/main/java/ninegle/Readio/adapter/service/NCloudStorageService.java, Readio/src/main/java/ninegle/Readio/book/controller/AdminBookController.java, Readio/src/main/java/ninegle/Readio/book/domain/Book.java, Readio/src/main/java/ninegle/Readio/book/domain/BookSearch.java, Readio/src/main/java/ninegle/Readio/book/dto/BookRequestDto.java, Readio/src/main/java/ninegle/Readio/book/mapper/BookMapper.java, Readio/src/main/java/ninegle/Readio/book/service/BookService.java
- 이미지, epub 파일 ncp 저장 및 수정 기능 구현
#87
=> feat: 책 추가, 수정 시 jpg,epub 파일  클라우드 등록 및 수정 기능 구현

frontend/src/App.tsx, frontend/src/pages/admin/AdminDashboard.tsx, frontend/src/pages/book/EpubReaderPage.tsx
=> feat: 책 읽기 API 연동

frontend/src/App.tsx, frontend/src/components/cs/faq.tsx, frontend/src/components/cs/notice.tsx, frontend/src/components/layout/Footer.tsx
=> [Feat] cs관련 프론트페이지 추가

frontend/src/pages/book/EpubReaderPage.tsx
=> [refactor] 뷰어페이지 전면 수정

Readio/src/main/java/ninegle/Readio/mypage/dto/response/PointResponseDto.java, Readio/src/main/java/ninegle/Readio/mypage/dto/response/UserInfoDto.java, Readio/src/main/java/ninegle/Readio/subscription/dto/response/SubscriptionResponseDto.java
=> [refactor] dto record로 변경

frontend/src/pages/member/LoginPage.tsx
=> [FE] LoginPage 수정

Readio/src/main/java/ninegle/Readio/book/dto/PaginationDto.java, Readio/src/main/java/ninegle/Readio/book/dto/preferencedto/PreferenceListResponseDto.java, Readio/src/main/java/ninegle/Readio/book/dto/preferencedto/PreferenceResponseDto.java, Readio/src/main/java/ninegle/Readio/book/dto/reviewdto/ReviewListResponseDto.java, Readio/src/main/java/ninegle/Readio/book/dto/reviewdto/ReviewResponseDto.java, Readio/src/main/java/ninegle/Readio/book/dto/reviewdto/ReviewSummaryDto.java, Readio/src/main/java/ninegle/Readio/global/exception/dto/ErrorResponse.java, Readio/src/main/java/ninegle/Readio/global/unit/BaseResponse.java
=> refactor:리뷰&관심목록 레코드화

Readio/src/main/java/ninegle/Readio/global/util/StringUtil.java, Readio/src/main/java/ninegle/Readio/mail/common/service/EmailService.java, Readio/src/main/java/ninegle/Readio/mail/subscription/scheduler/SubscriptionReminderScheduler.java, Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailSender.java, Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java, Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailSender.java, Readio/src/main/java/ninegle/Readio/mail/user/service/UserMailTemplateProvider.java
=> refactor : 메일 서비스 수정

Readio/src/main/java/ninegle/Readio/mail/subscription/scheduler/SubscriptionReminderScheduler.java, Readio/src/main/java/ninegle/Readio/mail/subscription/service/SubscriptionMailTemplateProvider.java, Readio/src/main/java/ninegle/Readio/subscription/domain/Subscription.java, Readio/src/main/java/ninegle/Readio/subscription/dto/response/SubscriptionResponseDto.java, Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionManager.java, Readio/src/main/java/ninegle/Readio/subscription/service/SubscriptionService.java
=> refactor : 구독수정

Readio/src/main/java/ninegle/Readio/book/repository/PreferencesRepository.java, Readio/src/main/java/ninegle/Readio/book/repository/ReviewRepository.java, Readio/src/main/java/ninegle/Readio/global/exception/domain/ErrorCode.java, Readio/src/main/java/ninegle/Readio/library/controller/LibraryBookController.java, Readio/src/main/java/ninegle/Readio/library/dto/book/LibraryDto.java, Readio/src/main/java/ninegle/Readio/library/dto/book/NewLibraryBookRequestDto.java, Readio/src/main/java/ninegle/Readio/library/dto/library/NewLibraryRequestDto.java, Readio/src/main/java/ninegle/Readio/library/dto/library/UpdateLibraryRequestDto.java, Readio/src/main/java/ninegle/Readio/library/mapper/LibraryBookMapper.java, Readio/src/main/java/ninegle/Readio/library/mapper/LibraryMapper.java, Readio/src/main/java/ninegle/Readio/library/repository/LibraryBookRepository.java, Readio/src/main/java/ninegle/Readio/library/repository/LibraryRepository.java, Readio/src/main/java/ninegle/Readio/library/service/LibraryBookService.java, Readio/src/main/java/ninegle/Readio/subscription/domain/Subscription.java, Readio/src/main/java/ninegle/Readio/subscription/repository/SubscriptionRepository.java, Readio/src/main/java/ninegle/Readio/tosspay/dto/TossPaymentConfirmRequestDto.java, Readio/src/main/java/ninegle/Readio/tosspay/service/PaymentService.java, Readio/src/main/java/ninegle/Readio/user/config/JwtAuthFilter.java, Readio/src/main/java/ninegle/Readio/user/controller/UserController.java, Readio/src/main/java/ninegle/Readio/user/domain/RefreshToken.java, Readio/src/main/java/ninegle/Readio/user/dto/Delete.java, Readio/src/main/java/ninegle/Readio/user/dto/DeleteUserRequestDto.java, Readio/src/main/java/ninegle/Readio/user/dto/LoginRequestDto.java, Readio/src/main/java/ninegle/Readio/user/dto/RefreshTokenRequestDto.java, Readio/src/main/java/ninegle/Readio/user/dto/SingUpRequestDto.java, Readio/src/main/java/ninegle/Readio/user/mapper/UserMapper.java, Readio/src/main/java/ninegle/Readio/user/repository/TokenRepository.java, Readio/src/main/java/ninegle/Readio/user/service/JwtTokenProvider.java, Readio/src/main/java/ninegle/Readio/user/service/UserService.java
=> feat: 회원탈퇴 구현, refactor: 레코드 형식으로 변경

frontend/src/pages/book/BookDetailPage.tsx, frontend/src/pages/book/EpubReaderPage.tsx
=> fix : fe: redirect 추가

frontend/src/pages/member/MyPage.tsx
=> Feat: deletebutton (#158)
